### ISSUE TITLE
Can't add a slideshow document

### ISSUE THREAD

**Issue by cmoulliard** [cmoulliard/hyla#119]
````
hyla add -t slideshow -a revealjs -d .
Config file to be parsed : /Users/chmoulli/RedHat/RH-Presentations/Business/enablement-cop/_config.yaml
>>   Fonts liberation added to project /Users/chmoulli/RedHat/RH-Presentations/Business/enablement-cop/fonts
/Users/chmoulli/.rbenv/versions/1.9.3-p484/lib/ruby/1.9.1/fileutils.rb:1515:in `stat': No such file or directory - /Users/chmoulli/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/hyla-1.0.7.pre.3/lib/templates/sample/asciidoc_revealjs.adoc (Errno::ENOENT)
	from /Users/chmoulli/.rbenv/versions/1.9.3-p484/lib/ruby/1.9.1/fileutils.rb:1515:in `block in fu_each_src_dest'
	from /Users/chmoulli/.rbenv/versions/1.9.3-p484/lib/ruby/1.9.1/fileutils.rb:1529:in `fu_each_src_dest0'
	from /Users/chmoulli/.rbenv/versions/1.9.3-p484/lib/ruby/1.9.1/fileutils.rb:1513:in `fu_each_src_dest'
	from /Users/chmoulli/.rbenv/versions/1.9.3-p484/lib/ruby/1.9.1/fileutils.rb:395:in `cp'
	from /Users/chmoulli/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/hyla-1.0.7.pre.3/lib/hyla/commands/add.rb:24:in `copy_artefact'
	from /Users/chmoulli/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/hyla-1.0.7.pre.3/lib/hyla/commands/add.rb:13:in `process'
	from /Users/chmoulli/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/hyla-1.0.7.pre.3/bin/hyla:68:in `block (2 levels) in <top (required)>'
	from /Users/chmoulli/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/commander-4.2.0/lib/commander/command.rb:180:in `call'
	from /Users/chmoulli/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/commander-4.2.0/lib/commander/command.rb:180:in `call'
	from /Users/chmoulli/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/commander-4.2.0/lib/commander/command.rb:155:in `run'
	from /Users/chmoulli/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/commander-4.2.0/lib/commander/runner.rb:421:in `run_active_command'
	from /Users/chmoulli/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/commander-4.2.0/lib/commander/runner.rb:81:in `run!'
	from /Users/chmoulli/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/commander-4.2.0/lib/commander/delegates.rb:12:in `run!'
	from /Users/chmoulli/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/commander-4.2.0/lib/commander/import.rb:10:in `block in <top (required)>'
````

**Comment by cmoulliard** [comment]
Command used wasn't correct. Should be : hyla add --t slideshow -a revealjs -d MyRevealSlideShow
